swagger: '2.0'

info:
  title: API
  version: '1.0'
  description: 'REST API interface'

basePath: /v1

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: API-KEY
  InternalApiKeyAuth:
    type: apiKey
    in: header
    name: API-KEY

security:
  - ApiKeyAuth: []
#paths:
#  /metrics:
#    $include: metrics/api.yaml
